name: Update Submodules

on:
  schedule:
    # 每6小时执行一次
    - cron:  '0 */6 * * *'
  push:
    # 当main分支有新的推送时执行
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          # 确保拉取所有子模块
          submodules: 'recursive'
          
      - name: setup-gh
        # You may pin to the exact commit or the version.
        # uses: wusatosi/setup-gh@7dae6c8246092454793fe35dd4d5a9e8bf8ed34d
        uses: wusatosi/setup-gh@v1.1
        with:
          # Repository setting for Github CLI
          repository: ${{ github.repository }}
          # Authentication token setting for Github CLI
          token: ${{ github.token }}

      - name: Init Submodules
        run: |
          git submodule init
          
      - name: Update Submodules
        run: |
          echo "update submodule"
          git submodule update --remote --recursive
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          echo "check submodule is changed or not"
          # Check if submodules have changed
          SUBMODULES_CHANGED=$(git submodule foreach --recursive 'git ls-files -m | grep . && echo "changed"' | grep "changed")
          if [ "x$SUBMODULES_CHANGED" != "x" ]; then
             echo "submodule is changed ,create new branch"
            # Create a new branch
            git checkout -b update-submodules-${{ github.run_id }}
             echo "commit change to the new branch"
            git commit -am "Automatically update submodules"
          
            # Push the branch and create a pull request
             echo "push the new branch update-submodules-${{ github.run_id }}"
            git push --set-upstream origin update-submodules-${{ github.run_id }}
            echo "create a PR"
            gh pr create --title "Auto-update submodules" --body "Automated changes to update submodules" --head update-submodules-${{ github.run_id }} --base main
          else
            echo "No changes in submodules."
          fi
